### ISSUE TITLE
Error using AGPermissions

### ISSUE THREAD

**Issue by felipesticksports** [TarasOsiris/android-goodies-docs-PRO#1]
Hi,

I'm trying to use the features regarding permissions from this package in our game but after invoking the method to request a permission nothing happens and I cannot understand why. Can you help me?

I'm only asking for the WRITE_EXTERNAL_STORAGE permission, which I have declared in my AndroidManifest like this:

`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />`

Which it makes the app asks for it as soon as it launches. To suppress that and control myself the request I've added this to my manifest as well:

`<meta-data android:name="unityplayer.SkipPermissionsDialog" android:value="true" />`

Ok, then I check for this permission using AGPermissions.IsPermissionGranted and when I get a negative response I show an internal pop up explaining to the user that our game needs this permission and will ask for it. As soon as the user clicks in our "Ok" button, I trigger the request just like the code from the GitHub page:

https://github.com/TarasOsiris/android-goodies-docs-PRO/wiki/AGPermissions.cs

But nothing happens. When checking LogCat messages I can see the activity was started but a couple of seconds later I see this warning there as well:"

`01-04 11:18:42.524: I/ActivityManager(1760): START u0 {cmp=com.sticksports.soccer2/com.deadmosquitogames.AndroidGoodiesActivity} from uid 10243 on display 0
01-04 11:18:46.033: W/GmsLocationProvider(18031): Error removing location updates: 16
01-04 11:18:51.082: W/MessageQueue(4033): Handler (alhb) {86f9dd2} sending message to a Handler on a dead thread
01-04 11:18:51.082: W/MessageQueue(4033): java.lang.IllegalStateException: Handler (alhb) {86f9dd2} sending message to a Handler on a dead thread
01-04 11:18:51.082: W/MessageQueue(4033): 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
01-04 11:18:51.082: W/MessageQueue(4033): 	at android.os.Handler.enqueueMessage(Handler.java:643)
01-04 11:18:51.082: W/MessageQueue(4033): 	at android.os.Handler.sendMessageAtTime(Handler.java:612)
01-04 11:18:51.082: W/MessageQueue(4033): 	at android.os.Handler.sendMessageDelayed(Handler.java:582)
01-04 11:18:51.082: W/MessageQueue(4033): 	at android.os.Handler.post(Handler.java:338)
01-04 11:18:51.082: W/MessageQueue(4033): 	at alhb.a(:com.google.android.gms:29)
01-04 11:18:51.082: W/MessageQueue(4033): 	at algt.a(:com.google.android.gms:3625)
01-04 11:18:51.082: W/MessageQueue(4033): 	at kbh.handleMessage(:com.google.android.gms:1540)
01-04 11:18:51.082: W/MessageQueue(4033): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-04 11:18:51.082: W/MessageQueue(4033): 	at android.os.Looper.loop(Looper.java:154)
01-04 11:18:51.082: W/MessageQueue(4033): 	at android.app.ActivityThread.main(ActivityThread.java:6119)
01-04 11:18:51.082: W/MessageQueue(4033): 	at java.lang.reflect.Method.invoke(Native Method)
01-04 11:18:51.082: W/MessageQueue(4033): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
01-04 11:18:51.082: W/MessageQueue(4033): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
`

Then nothing happens and my app keeps waiting for the callback that never arrives.

Just to make it clear, I'm testing in an Android 7.1.1, I do have android-support-v4.jar (but here it's actually support-v4-23.4.0.aar) and goodies-bridge-debug.release.jar in the Plugins/Android folder as well. Unity version is 5.4.3f1.

**Comment by TarasOsiris** [comment]
@felipesticksports do you also have all the permissions you are trying to request in the manifest file?

**Comment by felipesticksports** [comment]
Thanks for the quick reply.

Yes I do. I'm only asking for one "dangerous" permission and it's on the AndroidManifest file. The dialog from Google appears as normal as soon as the game launches, because that's how Unity works. But if I want to use your plugin and control that myself, as in, only request the permission when I want, I need to add this to the manifest as well:

`<meta-data android:name="unityplayer.SkipPermissionsDialog" android:value="true" />`

This will make unity not ask for the dangerous permissions during launch and then my game needs to handle itself, which is what I want.

The issue is, after I do request it like I explained in the above post, nothing happens except that warning in the logcat.

**Comment by TarasOsiris** [comment]
@felipesticksports I will check a bit later and get back to you asap. Meanwhile, can you please run the demo app in unitypackage and tell if it works as expected?

**Comment by felipesticksports** [comment]
I've tested the demo app using the SkipPermissionsDialog and targetSdkVersion to 24, which is what I use here and it worked as expected.

I wonder what might be causing this then. I even tried replacing the android-support-v4.jar shipped with your plugin with the support-v4-23.4.0.aar that I use on my game and it still works fine in the demo.

**Comment by TarasOsiris** [comment]
@felipesticksports this is really weird, I will try to investigate the issue on my side

**Comment by felipesticksports** [comment]
Ok found my mistake.

In the setup you say that we don't need to import your AndroidManifest if we have one (which will always be the case I think) and that the main activity was not overridden.  But I think it will be better to mention that this is still required:

`<activity android:name="com.deadmosquitogames.AndroidGoodiesActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar"></activity>`

Which is what was missing from mine. It's working fine now. Thanks!

**Comment by TarasOsiris** [comment]
@felipesticksports you are welcome! Thanks for pointing out, please write a review if you will enjoy the plugin and have a spare minute. 

Cheers.
